services:
  - type: web
    name: convolingo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapp.hackhazards_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0